name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-07"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTI3OGI0ODYtZDZiYS00NGFhLTk5MDMtNTg4Y2E0NDUxZDNmIiwidGVuYW50X2lkIjoiNTI0ZDI2MTNkMjBmY2FiNjU3ZDdmODMyNTZiY2NlYmYzZTMyNmZhNjhmMWZmYzYyOGZhNjlhNTcwNjRlYzZkMiIsImludGVybmFsX3NlY3JldCI6IjMzZTIxMTAwLTQ2YjItNDg1Ny1hZjNmLTEzZWQ2MmFmYzQ2YSJ9.r-KO3PW1DOpMeT6U7ZGyN_HnI1PkxLsehg2rPnCcL_Y"

JWT_SECRET="JWT_SECRET"